version: '3'
services:
  proxy:
    hostname: proxy
    image: jwilder/nginx-proxy
    container_name: proxydaw
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  web1:
    image: php:7.3-apache
    container_name: web1
    hostname: web1
    volumes:
      - ./sitios/web1:/var/www/html
    environment:
      - VIRTUAL_HOST=web1.com,www.web1.com
    restart: always
  web2:
    image: php:7.3-apache
    container_name: web2
    hostname: web2
    ports:
      - '81:80'
    volumes:
      - ./sitios/web2:/var/www/html
    environment:
      - VIRTUAL_HOST=web2.com,www.web2.com
    restart: always
